// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://birvtlrxhsyjhyorgwzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcnZ0bHJ4aHN5amh5b3Jnd3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTkwNDIsImV4cCI6MjA2ODI5NTA0Mn0.JHOtJCtBoiF_pDz8JeQFXTwlJ04EXmbQWSTDElrNfnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});